modLoader = "javafml"
loaderVersion = "[28,)"
[[mods]]
modId = "ultranotifier"
version = "${version}"
displayName = "${modName}"
description = "${description}"

[[dependencies.ultranotifier]]
modId="forge"
mandatory=true
versionRange="[28,)"
ordering="NONE"
side="BOTH"

[[dependencies.ultranotifier]]
modId="minecraft"
mandatory=true
versionRange="[${mcVersion}]"
ordering="NONE"
side="BOTH"